{% set name = "pado" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b2ec9d32ca89684ebb0670934a533314c89b607ca1a1de830b330f872338d43

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pado = pado.__main__:cli
    - pado-transporter = pado.transporter:cli_main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - dynaconf
    - fsspec
    - geojson-pydantic
    - itsdangerous
    - numpy >=1.21
    - opencv
    - orjson
    - pandas
    - platformdirs
    - pyarrow
    - pydantic
    - python >={{ python_min }}
    - rich >=12
    - shapely
    - tifffile >=2021.6.6
    - tiffslide >=1.7.0
    - toml
    - tqdm
    - typer
    - typing-extensions >=4.0

test:
  imports:
    - pado
    - pado.create
    - pado.dataset
    - pado.itertools
  commands:
    - pip check
    - pado --help
    - pado-transporter --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bayer-group/pado
  summary: cloud-native dataset library for accessing histopathological datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
